/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
        "surface-container-highest": "#34343d",
        "surface-bright": "#393841",
        "primary": "#c0c1ff",
        "inverse-primary": "#494bd6",
        "error": "#ffb4ab",
        "on-surface": "#e4e1ed",
        "surface-container-lowest": "#0d0d15",
        "secondary-fixed-dim": "#c0c6db",
        "surface-tint": "#c0c1ff",
        "background": "#13131b",
        "on-background": "#e4e1ed",
        "surface-container-low": "#1b1b23",
        "on-tertiary-container": "#452000",
        "on-tertiary-fixed": "#301400",
        "on-primary-fixed-variant": "#2f2ebe",
        "on-tertiary": "#4f2500",
        "outline-variant": "#464554",
        "on-tertiary-fixed-variant": "#703700",
        "surface-container": "#1f1f27",
        "secondary": "#c0c6db",
        "surface-variant": "#34343d",
        "on-primary-container": "#0d0096",
        "tertiary-fixed-dim": "#ffb783",
        "inverse-surface": "#e4e1ed",
        "outline": "#908fa0",
        "secondary-container": "#404758",
        "on-secondary": "#293040",
        "primary-fixed-dim": "#c0c1ff",
        "surface-container-high": "#292932",
        "on-error": "#690005",
        "secondary-fixed": "#dce2f7",
        "tertiary-fixed": "#ffdcc5",
        "on-primary-fixed": "#07006c",
        "surface": "#13131b",
        "on-surface-variant": "#c7c4d7",
        "inverse-on-surface": "#303038",
        "on-error-container": "#ffdad6",
        "surface-dim": "#13131b",
        "on-secondary-fixed": "#141b2b",
        "on-secondary-fixed-variant": "#404758",
        "primary-container": "#8083ff",
        "on-secondary-container": "#aeb5c9",
        "on-primary": "#1000a9",
        "tertiary": "#ffb783",
        "tertiary-container": "#d97721",
        "error-container": "#93000a",
        "primary-fixed": "#e1e0ff"
      },
      "borderRadius": {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      "spacing": {
        "margin": "24px",
        "sm": "8px",
        "lg": "24px",
        "md": "16px",
        "xs": "4px",
        "xl": "32px",
        "unit": "4px",
        "gutter": "20px"
      },
      "fontFamily": {
        "headline-lg": ["Inter", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
        "headline-xl": ["Inter", "sans-serif"],
        "headline-md": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "headline-xl-mobile": ["Inter", "sans-serif"]
      },
      "fontSize": {
        "headline-lg": ["24px", { "lineHeight": "1.3", "letterSpacing": "-0.01em", "fontWeight": "600" }],
        "label-md": ["12px", { "lineHeight": "1", "letterSpacing": "0.02em", "fontWeight": "500" }],
        "headline-xl": ["36px", { "lineHeight": "1.2", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "headline-md": ["20px", { "lineHeight": "1.4", "fontWeight": "600" }],
        "body-md": ["14px", { "lineHeight": "1.5", "fontWeight": "400" }],
        "body-lg": ["16px", { "lineHeight": "1.6", "fontWeight": "400" }],
        "headline-xl-mobile": ["28px", { "lineHeight": "1.2", "fontWeight": "700" }]
      }
    },
  },
  plugins: [],
}
